-- Restart input file generated by LSMS
systemid="al"
system_title="TiAl test for LSMS 3"
pot_in_type=1
pot_out_type=1
lsmsMode="main"
lsmsAlgorithms={0, 0}
istop="main"

nscf=50
writeSteps=30000

rmsTolerance=1e-16

energyTolerance=1e-06

print_node=0
default_iprint=-2
iprint=-1

iprpts=1051
ipcore=30

infoEvecFileOut="info_evec_out"

gpu_threads=1
num_atoms=1
relativity="scalar"
core_relativity="full"
mtasa=1
fixRMT=0
nspin=1
xcFunctional={1,1,7}

energyContour={}
energyContour.grid=2
energyContour.npts=32
energyContour.ebot=-0.300000
energyContour.etop=0.000000
energyContour.eibot=0.002500
energyContour.eitop=0.825000
energyContour.maxGroupSize=50

adjustContourBottom=-1.000000

temperature=0.000000

mixing={ bravais={}
bravais[1]={    4.393614990825376,     4.393614990825376,     0.000000000000000}
bravais[2]={    0.000000000000000,     4.393614990825376,     4.393614990825376}
bravais[3]={    4.393614990825376,     0.000000000000000,     4.393614990825376}

site={}
for i =1,num_atoms do site[i]={} end

site[1].pos={    0.000000000000000,     0.000000000000000,     0.000000000000000}
site[1].evec={    0.000000000000000,     0.000000000000000,     1.000000000000000}
site[1].atom="Al"
site[1].lmax=3
site[1].Z=13
site[1].Zc=2
site[1].Zs=8
site[1].Zv=3
site[1].rLIZ=10.333333
site[1].rsteps={89.500000,91.500000,93.200000,99.900000}
site[1].rad=2.000000
