# Toolchain for building LSMS with CUDA on OLCF Summit

set(USE_ACCELERATOR_CUDA_C ON)
set(USE_ESSL ON)
set(ARCH_IBM ON)
set(MST_LINEAR_SOLVER_DEFAULT 0x0013)
set(MST_BUILD_KKR_MATRIX_DEFAULT 0x3000)

